(define (problem ISTDP)
  (:domain RFIStation)
  (:objects)
  (:init
    (trainEntersStationAt T1 F02)
    (= (time ) 0)
    (= (timeElapsedReservedItinerary I1) 0)
    (= (timeElapsedReservedItinerary I2) 0)
    (= (timeElapsedReservedItinerary I3) 0)
    (= (timeElapsedOverlappedFlag F_I) 0)
    (= (timeElapsedOverlappedFlag F_II) 0)
    (= (timeElapsedOverlappedFlag F_III) 0)
    (= (trainsEnteredFromEndpoint EP1) 0)
    (= (trainsArrivedAtEndpoint EP1) 0)
    (= (trainStayInStation T1) 0)
    (= (trainTimeFromArrival T1) 0)
    (= (trainEntryIndex T1) 0)
  )
  (:goal
    (and
      (<= (trainStayInStation T1) 100)
      (trainExitsStationAt T1 F_IV)
      (trainHasStopped T1)
      (trainHasStoppedAtStop T1 S_I)
    )
  )
)
