(define (problem Prob)
	(:domain RFIStation)
	(:objects
	)
	(:init
		(trainEntersStationAt T1 F01)
		(= (time ) 0)
		(= (timeElapsedReservedItinerary IW1) 0)
		(= (timeElapsedReservedItinerary IW2) 0)
		(= (timeElapsedReservedItinerary IW3) 0)
		(= (timeElapsedReservedItinerary IW4) 0)
		(= (timeElapsedReservedItinerary IW5) 0)
		(= (timeElapsedReservedItinerary I1E) 0)
		(= (timeElapsedReservedItinerary I2E) 0)
		(= (timeElapsedReservedItinerary I3E) 0)
		(= (timeElapsedReservedItinerary I4E) 0)
		(= (timeElapsedReservedItinerary I5E) 0)
		(= (timeElapsedReservedItinerary IE1) 0)
		(= (timeElapsedReservedItinerary IE2) 0)
		(= (timeElapsedReservedItinerary IE3) 0)
		(= (timeElapsedReservedItinerary IE4) 0)
		(= (timeElapsedReservedItinerary IE5) 0)
		(= (timeElapsedReservedItinerary I1W) 0)
		(= (timeElapsedReservedItinerary I2W) 0)
		(= (timeElapsedReservedItinerary I3W) 0)
		(= (timeElapsedReservedItinerary I4W) 0)
		(= (timeElapsedReservedItinerary I5W) 0)
		(= (timeElapsedOverlappedFlag F01) 0)
		(= (timeElapsedOverlappedFlag F1R) 0)
		(= (timeElapsedOverlappedFlag F2R) 0)
		(= (timeElapsedOverlappedFlag F3R) 0)
		(= (timeElapsedOverlappedFlag F4R) 0)
		(= (timeElapsedOverlappedFlag F5R) 0)
		(= (timeElapsedOverlappedFlag F03) 0)
		(= (timeElapsedOverlappedFlag F04) 0)
		(= (timeElapsedOverlappedFlag F1L) 0)
		(= (timeElapsedOverlappedFlag F2L) 0)
		(= (timeElapsedOverlappedFlag F3L) 0)
		(= (timeElapsedOverlappedFlag F4L) 0)
		(= (timeElapsedOverlappedFlag F5L) 0)
		(= (timeElapsedOverlappedFlag F02) 0)
		(= (trainsEnteredFromEndpoint W_plus) 0)
		(= (trainsArrivedAtEndpoint W_plus) 0)
		(= (trainsEnteredFromEndpoint W_minus) 0)
		(= (trainsArrivedAtEndpoint W_minus) 0)
		(= (trainsEnteredFromEndpoint E_minus) 0)
		(= (trainsArrivedAtEndpoint E_minus) 0)
		(= (trainsEnteredFromEndpoint E_plus) 0)
		(= (trainsArrivedAtEndpoint E_plus) 0)
		(= (trainStayInStation T1) 0)
		(= (trainTimeFromArrival T1) 0)
		(= (trainEntryIndex T1) 0)
	)
	(:goal
		(and
			(<= (trainStayInStation T1) 30)
			(trainExitsStationAt T1 F03)
			(trainHasStopped T1)
		)
	)
)
