(define (problem Prob)
	(:domain RFIStation)
	(:objects
	)
	(:init
		(trainEntersStationAt T1 F01)
		(trainEntersStationAt T2 F01)
		(trainEntersStationAt T3 F04)
		(trainEntersStationAt T4 F04)
		(trainHasStoppedAtStop T5 S_I)
		(trainHasStopped T5)
		(trainIsStoppingAtStop T5 S_I)
		(trainIsStopping T5)
		(stopIsOccupied S_I)
		(binBitIsBlocked cdbap)
		(binBitIsBlocked cdbau)
		(binBitIsBlocked cdbaz)
		(= (time ) 0)
		(= (timeElapsedReservedItinerary IW1) 0)
		(= (timeElapsedReservedItinerary IW2) 0)
		(= (timeElapsedReservedItinerary IW3) 0)
		(= (timeElapsedReservedItinerary IW4) 0)
		(= (timeElapsedReservedItinerary IW5) 0)
		(= (timeElapsedReservedItinerary I1E) 0)
		(= (timeElapsedReservedItinerary I2E) 0)
		(= (timeElapsedReservedItinerary I3E) 0)
		(= (timeElapsedReservedItinerary I4E) 0)
		(= (timeElapsedReservedItinerary I5E) 0)
		(= (timeElapsedReservedItinerary IE1) 0)
		(= (timeElapsedReservedItinerary IE2) 0)
		(= (timeElapsedReservedItinerary IE3) 0)
		(= (timeElapsedReservedItinerary IE4) 0)
		(= (timeElapsedReservedItinerary IE5) 0)
		(= (timeElapsedReservedItinerary I1W) 0)
		(= (timeElapsedReservedItinerary I2W) 0)
		(= (timeElapsedReservedItinerary I3W) 0)
		(= (timeElapsedReservedItinerary I4W) 0)
		(= (timeElapsedReservedItinerary I5W) 0)
		(= (timeElapsedOverlappedFlag F01) 0)
		(= (timeElapsedOverlappedFlag F1R) 0)
		(= (timeElapsedOverlappedFlag F2R) 0)
		(= (timeElapsedOverlappedFlag F3R) 0)
		(= (timeElapsedOverlappedFlag F4R) 0)
		(= (timeElapsedOverlappedFlag F5R) 0)
		(= (timeElapsedOverlappedFlag F03) 0)
		(= (timeElapsedOverlappedFlag F04) 0)
		(= (timeElapsedOverlappedFlag F1L) 0)
		(= (timeElapsedOverlappedFlag F2L) 0)
		(= (timeElapsedOverlappedFlag F3L) 0)
		(= (timeElapsedOverlappedFlag F4L) 0)
		(= (timeElapsedOverlappedFlag F5L) 0)
		(= (timeElapsedOverlappedFlag F02) 0)
		(= (trainsEnteredFromEndpoint W_plus) 0)
		(= (trainsArrivedAtEndpoint W_plus) 0)
		(= (trainsEnteredFromEndpoint W_minus) 0)
		(= (trainsArrivedAtEndpoint W_minus) 0)
		(= (trainsEnteredFromEndpoint E_minus) 0)
		(= (trainsArrivedAtEndpoint E_minus) 0)
		(= (trainsEnteredFromEndpoint E_plus) 0)
		(= (trainsArrivedAtEndpoint E_plus) 0)
		(= (trainStayInStation T1) 0)
		(= (trainTimeFromArrival T1) 0)
		(= (trainEntryIndex T1) 0)
		(= (trainStayInStation T2) 0)
		(= (trainTimeFromArrival T2) 0)
		(= (trainEntryIndex T2) 0)
		(= (trainStayInStation T3) 0)
		(= (trainTimeFromArrival T3) 0)
		(= (trainEntryIndex T3) 0)
		(= (trainStayInStation T4) 0)
		(= (trainTimeFromArrival T4) 0)
		(= (trainEntryIndex T4) 0)
		(= (trainStayInStation T5) 0)
		(= (trainTimeFromArrival T5) 0)
		(= (trainEntryIndex T5) 0)
	)
	(:goal
		(and
			(<= (trainStayInStation T1) 757)
			(trainHasEndedVoy T1)
			(trainHasStopped T1)
			(trainHasStoppedAtStop T1 S_II)
			(<= (trainStayInStation T2) 717)
			(trainExitsStationAt T2 F03)
			(trainHasStopped T2)
			(<= (trainStayInStation T3) 891)
			(trainExitsStationAt T3 F02)
			(<= (trainStayInStation T4) 816)
			(trainExitsStationAt T4 F02)
			(trainHasStopped T4)
			(<= (trainStayInStation T5) 553)
			(trainExitsStationAt T5 F02)
			(trainHasStopped T5)
			(trainHasStoppedAtStop T5 S_I)
		)
	)
)
